version: '3.8'

services:
  web:
    image: python:3.11
    container_name: voici-ai-web
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: python -m http.server 8000
    restart: unless-stopped